# -*- coding: utf-8 -*-
"""class05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbW6rltOkaheJ-mDORvpNa7FJFOdDEEc
"""



"""# take a two input print sum,sub,mul,division and remainder"""

num1=int(input('enter num1 :'))
num2=int(input('enter num2 :'))

sum=num1+num2
sub=num1-num2
mul=num1*num2
div=num1/num2
rem=num1%num2

from re import S
print(sum)
print(sub)
print(mul)
print(div)
print(rem)



num1=int(input('enter num1 :'))
num2=int(input('enter num2 :'))
num3=int(input('enter num3 :'))

sum=num1+num2+num3
sub=num1-num2-num3
mul=num1*num2*num3
div=num1/num2/num3
rem=num1%num2%num3

print (sum)
print (sub)
print (mul)
print (div)
print (rem)