# -*- coding: utf-8 -*-
"""class04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NNbIhoWM2KHXuhOD4G3auYZbO0HprGcq
"""



"""# ami ekhane kivabe input niye kaj korte hoy ta bekkha korbo

"""



name=input('enter your nname :')
print(name)

colege=input('college name :')
print(colege)

address=input('enter your address:')
print(address)

age1=int(input('enter tanvir age' ))
age2=int(input('enter sumon age'))
total=age1+age2
print(age1)
print(age2)
print('total :',total)